#!/bin/bash

#
# script extracts create date from exif metadata included in image
# next moving file into YYYY-MM/YYYY-MM-DD_H:m:s.ext
#

[[ -z ${1} ]] && echo -e "\e[1;37mSyntax: $(basename ${0}) <photo directory>\e[0m" && exit 1
[[ ! -d ${1} ]] && echo -e "\e[1;31mError: no such directory ${1}\e[0m" && exit 1
[[ ! -x /usr/bin/exiftool ]] && echo -e "\e[1;31mError: no exiftool found\e[0m" && exit 1

TS=$(date +%Y%m%d%H%M%S)
FILE=/tmp/photo-organizer-${TS}

echo "Writing into ${FILE}" 
find ${1} -type f > ${FILE}

while read file
do
	ext="${file##*.}"
	# echo $file $ext

	dst=$(exiftool ${file} | grep "Create Date" | head -n 1 | perl -lne 'print "$1-$2-$3_$4:$5:$6" if /(\d+):(\d+):(\d+) (\d+):(\d+):(\d+)/')
	dst_dir="${dst:0:7}"

	if [ -z $dst ] ; then
		echo "Skipping ${file}"
	else
		dir="${file%.*}"
		[[ ! -d ${dst_dir} ]] && mkdir "${dst_dir}"
		[[ -d ${dst_dir} ]] && mv -v "${file}" "${dst_dir}/${dst}.${ext}"
	fi
done < ${FILE}
rm ${FILE}
